### ISSUE TITLE
Upgrade smart contract doesn't work through command palette

### ISSUE THREAD

**Issue by james-wallis** [IBM-Blockchain/blockchain-vscode-extension#2806] opened 2020-11-11 18:28 UTC
## Description

Instead of using the Deploy view I wanted to use the command palette

## Expected Behavior

One of:
1. Upgrade a contract
2. Not exist as we have the view now 
3. Open the deploy view

IMO we should do 1 or 3 with 3 being the easiest as it can just open the view.

## Actual Behavior

The extension tries to upgrade the contract but throws an error in vscode:
![image](https://user-images.githubusercontent.com/17385115/98849678-7e987580-244b-11eb-9ef8-a65209fa15a5.png)

**Comment by Jakeeyturner** [comment] 2020-11-12 11:51
The problem is caused by following the v1 install, instantiate and upgrade flow.

Install, instantiate and upgrade shouldn't be visible from the command palette - fixed in https://github.com/IBM-Blockchain/blockchain-vscode-extension/pull/2808

**Closed by Jakeeyturner** 2020-11-12 11:51 UTC
Labels: bug, v2
