### ISSUE TITLE
External gateway does not show up when configuring Wallet creds

### ISSUE THREAD

**Issue by drmiller4** [IBM-Blockchain/blockchain-vscode-extension#1895] opened 2020-02-11 12:27 UTC
## Description
Created an external Gateway in the VSCode IBM Blockchain Platform extension to point to my IBP V2.x version on OpenShift 3.1.1. I then tried to create a wallet and then told it to use select a gateway and provide an enrollment ID and secret. However the drop down does not allow me to select my external gateway I configured (does not even show up in a drop down). I reverted back to 1.0.18 of the extension and my external gateway shows up in the drop down list.

## Expected Behavior
You should see your external gateways show up in a drop down list.

## Actual Behavior
The external gateways do not show up.

## Possible Fix
I reverted back to 1.0.18 of the extension and my external gateway shows up in the drop down list.

## Steps to Reproduce

1.
2.
3.

## Your Environment

* IBM Blockchain Platform Extension Version: 1.0.19
* Visual Studio Code version: 1.39.2
* Environment name and version (e.g. Node.js v8.12.0, npm v6.4.1): Node.js v8.17.0 npm 6.13.4
* Operating System and version: MacOSX 10.15.3
* Link to your project:

**Comment by Jakeeyturner** [comment] 2020-02-11 12:36
Duplicate of #1894

**Closed by Jakeeyturner** 2020-02-11 12:36 UTC
