### ISSUE TITLE
Can't supply a stringified JSON object through vscode 'SubmitTransaction'

### ISSUE THREAD

**Issue by jpayne23** [IBM-Blockchain/blockchain-vscode-extension#765] opened 2019-03-26 16:58 UTC
## Description
When using the 'Submit Transaction' command on the VSCode plugin the command asks you to supply the arguments for that transaction. The arguments are expected as a comma delimited list which causes issues when you need to pass in a stringified JSON object with multiple properties as it interprets each property in the JSON object as a separate argument.

This leads to chaincode erroring with a number of arguments mismatch error.

We have tried escaping the commas and quotes within the JSON object but this makes no difference.

## Expected Behavior
I am able to provide a stringified JSON object as an argument when using the 'Submit Transaction' command on the vscode plugin

## Actual Behavior
The plugin splits a stringified JSON object into multiple separate arguments based on the number of properties in that object.

## Possible Fix
Ignore commas within a JSON object when creating the array of arguments to pass to the transaction.

## Steps to Reproduce
1. Deploy chaincode
2. Execute the 'Submit Transaction' command on a transaction that expects a stringified JSON object
3. Try to provide a stringified JSON object
4. Get an error stating number of arguments mismatch

## Existing Issues
None found

## Log File
`[3/26/2019 4:57:35 PM] [INFO] fabricvscodelocalfabric_peer0.org1.example.com|2019-03-26 16:57:35.366 UTC [endorser] SimulateProposal -> ERRO 5fb [mychannel][3364c5cc] failed to invoke chaincode name:“device-access” , error: transaction returned with failure: Error: Expected 1 parameters, but 3 have been supplied`

## Your Environment

* IBM Blockchain Platform Extension Version: 0.3.2
* Visual Studio Code version: 1.32.3

**Comment by caroline-church** [comment] 2019-03-26 17:35
closing as a duplicate of #719

**Closed by caroline-church** 2019-03-26 17:35 UTC
