### ISSUE TITLE
Failed to Create new project

### ISSUE THREAD

**Issue by dhruvd2018** [IBM-Blockchain/blockchain-vscode-extension#2831] opened 2020-11-26 15:19 UTC
Getting error when trying to create project I have attached image of the error and my screen please advise. 

Error: Could not rebuild native dependencies Failed to execute command "npm" with arguments "rebuild, grpc, --target=9.3.3, --runtime=electron, --update-binary, --fallback-to-build, --target_arch=x64, --dist-url=https://atom.io/download/electron" return code 1. Please ensure that you have node and npm installed

[main.log](https://github.com/IBM-Blockchain/blockchain-vscode-extension/files/5603800/main.log)

* Link to your project:
<img width="1675" alt="image" src="https://user-images.githubusercontent.com/34627558/100367712-a30a5b00-2fd0-11eb-83a9-0e6748486e6e.png">

**Comment by Jakeeyturner** [comment] 2020-11-27 09:29
Duplicate of issue #1621.

**Closed** 2020-11-27 09:29 UTC
