### ISSUE TITLE
Failed to load extension

### ISSUE THREAD

**Issue by 26rahulsingh** [IBM-Blockchain/blockchain-vscode-extension#398] opened 2018-12-03 08:15 UTC
NodeJS v8.13.0 installed using NVM
npm version 6.4.1
Ubuntu 18.04

extension activating
Updating native node modules
Rebuilding native node modules
Could not rebuild native dependencies spawn npm ENOENT. Please ensure that you have node and npm installed
Failed to activate extension see previous messages for reason

**Comment by heatherlp** [comment] 2018-12-06 10:41
Hi @26rahulsingh - can you retry this with the latest version of the extension? It's 0.0.7

**Comment by 26rahulsingh** [comment] 2018-12-06 10:45
Hello @heatherlp - I got the same error with the latest version 0.0.7

**Comment by shineparamel** [comment] 2018-12-07 22:48
Same here. Is there any possibility to try in the previous version

**Comment by heatherlp** [comment] 2018-12-12 12:20
@shineparamel are you on Ubuntu too?

**Comment by mahoney1** [comment] 2018-12-12 12:41
As discussed @heatherlp  - Also using Ubuntu. v16.04.1 with node 8.11.4, npm 5.6. Tried with IBP VSCode ext 0.1.0 and get the same 
![image](https://user-images.githubusercontent.com/22452289/49870365-0f531a80-fe0b-11e8-9c51-412c5f2b2cc7.png)

**Comment by rthatcher** [comment] 2018-12-12 15:01
v0.1.0 activates OK on my Ubuntu VM - Ubuntu 18.04.1 LTS

**Comment by mahoney1** [comment] 2018-12-12 15:57
FYI got it working (activated!). Here's what I did: 1) uninstalled node 8.11.4, npm 5.6 completely on my system. 2) I then reinstalled (node 8.11.4 again, but with npm 6.4.1. 3) I removed the ibm-blockchainxx extension (directory) from $HOME/.vscode. 4) I launched VSCode, installed the extension, 0.1.0 and reloaded/activated, got past the rebuild. output below.
```Updating native node modules
Rebuilding native node modules

> grpc@1.14.2 install /home/ibm/.vscode/extensions/ibmblockchain.ibm-blockchain-platform-0.1.0/node_modules/grpc
> node-pre-gyp install --fallback-to-build --library=static_library
node-pre-gyp
 
WARN
 Using request for node-pre-gyp https download 
[grpc] Success: "/home/ibm/.vscode/extensions/ibmblockchain.ibm-blockchain-platform-0.1.0/node_modules/grpc/src/node/extension_binary/electron-v2.0-linux-x64-glibc/grpc_node.node" is installed via remote
grpc@1.14.2 /home/ibm/.vscode/extensions/ibmblockchain.ibm-blockchain-platform-0.1.0/node_modules/grpc
Updating grpc
Finished updating native node modules
extension activated```

**Comment by piaste** [comment] 2018-12-12 17:14
I'm encountering a failure with a similar but not identical reason:

```
extension activating
Updating native node modules
Rebuilding native node modules

> grpc@1.14.2 install C:\Users\piaste\.vscode\extensions\ibmblockchain.ibm-blockchain-platform-0.1.0\node_modules\grpc
> node-pre-gyp install --fallback-to-build --library=static_library
node-pre-gyp
 WARN Using request for node-pre-gyp https download 
[grpc] Success: "C:\Users\piaste\.vscode\extensions\ibmblockchain.ibm-blockchain-platform-0.1.0\node_modules\grpc\src\node\extension_binary\electron-v2.0-win32-x64-unknown\grpc_node.node" already installed
Pass --update-binary to reinstall or --build-from-source to recompile
grpc@1.14.2 C:\Users\piaste\.vscode\extensions\ibmblockchain.ibm-blockchain-platform-0.1.0\node_modules\grpc
Updating grpc
Failed to activate extension see previous messages for reason
```

Environment: 

Win10 x64 1803
Node 10.14.2
npm 6.4.1
VSCode 1.29.1

Completely wiped and reinstalled Node and npm and cleared the extension folder just to be sure, no change.

I looked at the [source for the dependency installer](https://github.com/IBM-Blockchain/blockchain-vscode-extension/blob/b608eac1d8c622ee0eab46bb4829d9123311f654/client/src/dependencies/DependencyManager.ts#L82), and the command executed should be this:

```
npm rebuild grpc@1.14.2 --target=2.0.0 --runtime=electron --dist-url=https://atom.io/download/electron --verbose
```

which completes successfully if I run it manually from the extension folder, with the same log as above (minus the last two lines)

Since I don't get the `Finished updating native node modules` log nor the `Could not rebuild native dependencies` one, and `grpc` is the only native dependency, I'm not sure where to look next.

**Comment by rthatcher** [comment] 2018-12-12 17:31
I _think_ there is a problem with grpc and Node v10 - can you try Node v8 instead of Node v10?

**Comment by shineparamel** [comment] 2018-12-13 22:56
> @shineparamel are you on Ubuntu too?

Yes Ubuntu

**Comment by piaste** [comment] 2019-01-02 09:55
@rthatcher 

Thanks, installing 8 fixed that issue  :)

I later tried upgrading to 11 to see if it solved another problem (see #436) and the error didn't reappear either.

**Comment by jentityframework** [comment] 2019-03-28 02:05
@piaste 
Can you run with node 11?

**Comment by jentityframework** [comment] 2019-03-28 02:16
NodeJS: v11.12.0
npm: 6.9.0
yo: 2.0.5
Docker version 18.09.2, build 6247962
docker-compose version 1.23.2, build 1110ad01

[3/28/2019 8:32:13 AM] [IMPORTANT] Log files can be found by running the `Developer: Open Logs Folder` command from the palette

[3/28/2019 8:32:14 AM] [INFO] Starting IBM Blockchain Platform Extension
[3/28/2019 8:32:14 AM] [INFO] Updating native node modules
[3/28/2019 8:32:14 AM] [INFO] Rebuilding native node modules
[3/28/2019 8:32:34 AM] [INFO] > grpc@1.17.0 install C:\Users\Tri Phan\.vscode\extensions\ibmblockchain.ibm-blockchain-platform-0.3.2\node_modules\grpc
[3/28/2019 8:32:34 AM] [INFO] > node-pre-gyp install --fallback-to-build --library=static_library
[3/28/2019 8:32:36 AM] [INFO] node-pre-gyp
[3/28/2019 8:32:36 AM] [INFO]  
[3/28/2019 8:32:36 AM] [INFO] WARN Using request for node-pre-gyp https download 
[3/28/2019 8:32:38 AM] [INFO] [grpc] Success: "C:\Users\Tri Phan\.vscode\extensions\ibmblockchain.ibm-blockchain-platform-0.3.2\node_modules\grpc\src\node\extension_binary\electron-v3.0-win32-x64-unknown\grpc_node.node" is installed via remote
[3/28/2019 8:32:38 AM] [INFO] grpc@1.17.0 C:\Users\Tri Phan\.vscode\extensions\ibmblockchain.ibm-blockchain-platform-0.3.2\node_modules\grpc
[3/28/2019 8:32:38 AM] [INFO] Updating grpc
[3/28/2019 8:32:38 AM] [ERROR] Failed to activate extension see previous messages for reason

**Comment by kafcioo** [comment] 2019-04-29 12:07
I have the same problem and duno where to look now for a solution
Running Ubuntu 16.4
npm 5.10
node 8.16
and all other Prerequisites  seem to have correct versioning

**Comment by jentityframework** [comment] 2019-04-29 15:01
@kafcioo: I suggest you remove installation folder of this extions and reinstall again. I did with this way and I can run it now

**Comment by Raumo0** [comment] 2019-05-12 19:24
**This error still exists, I have this problem.** I cannot install the blockchain vscode extension.
```

[5/12/2019 4:51:37 PM] [IMPORTANT] Log files can be found by running the `Developer: Open Logs Folder` command from the palette

[5/12/2019 4:51:37 PM] [INFO] Starting IBM Blockchain Platform Extension
[5/12/2019 4:51:37 PM] [INFO] Updating native node modules
[5/12/2019 4:51:37 PM] [INFO] Rebuilding native node modules
[5/12/2019 4:51:37 PM] [ERROR] Could not rebuild native dependencies spawn npm ENOENT. Please ensure that you have node and npm installed
[5/12/2019 4:51:37 PM] [ERROR] Failed to activate extension see previous messages for reason

```
I tried to reinstall nvm, node, npm, yo.. reinstall the extension with installetion folder, reinstall vscode etc.

**My dev env:**
```
nvm:0.34.0
node:8.11.4, 10.0.0, 11.0.0 12.2.0
npm:5.6.0, 6.4.1, 6.9.0
yo:2.0.6
vscode:Version: 1.33.1
OS:Ubuntu 18.04.1
```
@jentityframework , @mahoney1 I also tried the options you suggested, but they did not help me.
@Jakeeyturner

**Comment by bernarddk** [comment] 2019-05-13 12:13
Same issue as @Raumo

nvm:0.34.0
node:8.9.4
npm:5.6.0
vscode:Version: 1.33.1
MacOS 10.14.4

**Comment by jessezwd** [comment] 2019-07-10 01:41
Same issue under Archlinux:
node: 10.16.0
npm: 5.9.0
vscode: 1.36.1
OS: Linux x64 5.1.15-1-MANJARO

**Comment by cazfletch** [comment] 2019-07-10 07:03
Do you have the error message? Also if you scroll back in the log are there any other errors?

**Comment by Jazibabdullah** [comment] 2019-07-10 14:47
Same issue 

solved by just running command 'npm install --save-dev electron-rebuild'

**Comment by jessezwd** [comment] 2019-07-11 00:53
@cazfletch the error message is the following:
Could not rebuild native dependencies Failed to execute command "npm" with  arguments "rebuild, grpc, --target=4.2.5, --runtime=electron, --dist-url=https://atom.io/download/electron, --update-binary, --fallback-to-build, --target_arch=x64" return code 1. Please ensure that you have node and npm installed

**Comment by Jazibabdullah** [comment] 2019-07-11 04:55
Same issue as @jessezwd
npm : 6.10.0
node :v12.6.0
code : 1.36.1
OS : Windows 10

**Comment by mloetscher** [comment] 2019-07-11 11:49
Same issue here:
npm : 6.10.0
node : v10.16.0
code : 1.36.1
OS : macOS 10.14.5

**Comment by LuisGitHub1** [comment] 2019-07-13 07:04
Same issue here:
npm: 6.9.0
node: v12.6.0
cod: 1.36.1
OS: MacOS 10.14.5

is there any fix or workaround available for this?

**Comment by shineparamel** [comment] 2019-07-13 08:08
Hi,

Even I had this same issue with VS code... I just installed the same in root... Issues got solved. Just try once

Sent from ProtonMail mobile

-------- Original Message --------

**Comment by jessezwd** [comment] 2019-07-13 09:18
@shineparamel Hi, there.  install what exactly in root? and how? Thanks for your comments.

**Comment by shineparamel** [comment] 2019-07-15 13:37
Hi,

As per pre-requisites you need to install npm, node, nvm, yo .... Kindly install these in the root access too.... After installation in root it started to work for me

Sent from ProtonMail mobile

-------- Original Message --------

**Comment by cazfletch** [comment] 2019-07-17 14:32
closing as version 1.0.5 should fix this. If you are still having issues please open a new issue for it

**Closed by cazfletch** 2019-07-17 14:32 UTC
Labels: bug, sev1

**Comment by feras-shamashan-coriel** [comment] 2019-08-12 14:46
@cazfletch, I installed the extension and it worked once only and in the  next time I tried to use  it, it stopped working throwing the following error:

Could not rebuild native dependencies spawn npm ENOENT. Please ensure that you have node and npm installed. 

Failed to activate extension: spawn npm ENOENT.

node: v8.16.0
npm:  6.4.1
I am using ubuntu as VM.

So far, I have tried the following:

1 - different version od node and npm
2- delete and install node again 

Wondering if you have any other suggestions about that!

Thanks in advance :)

**Comment by cazfletch** [comment] 2019-08-12 14:50
Hi @feras-shamashan-coriel if from the terminal inside vscode what happens if you run `npm --version`?

**Comment by feras-shamashan-coriel** [comment] 2019-08-12 14:56
Hi @cazfletch, thank you for your replay. Inside the vscode terminal: 
node --version  v8.16.0
npm --version  6.4.1

**Comment by cazfletch** [comment] 2019-08-12 15:00
how is node and npm installed?

**Comment by feras-shamashan-coriel** [comment] 2019-08-12 15:03
I have used those command: 

sudo apt-get install nodejs
sudo apt-get install npm

**Comment by cazfletch** [comment] 2019-08-12 15:04
did you have to update any env vars after?

**Comment by feras-shamashan-coriel** [comment] 2019-08-12 15:07
No, I didn't change anything. It was working, I restarted my OS and it stopped.

**Comment by feras-shamashan-coriel** [comment] 2019-08-12 15:49
If this log could help: 

[12/08/2019 16:26:24] [IMPORTANT] Log files can be found by running the `Developer: Open Logs Folder` command from the palette

[12/08/2019 16:26:24] [INFO] Starting IBM Blockchain Platform Extension
[12/08/2019 16:26:24] [INFO] Attempting to require dependency: grpc
[12/08/2019 16:26:24] [INFO] Error requiring dependency: The gRPC binary module was not installed. This may be fixed by running "npm rebuild"
Original error: Cannot find module '/home/xxxxxx/.vscode/extensions/ibmblockchain.ibm-blockchain-platform-1.0.6/node_modules/grpc/src/node/extension_binary/node-v69-linux-x64-glibc/grpc_node.node'
[12/08/2019 16:26:24] [INFO] Updating native node modules
[12/08/2019 16:26:24] [INFO] Rebuilding native node modules
[12/08/2019 16:26:24] [ERROR] Could not rebuild native dependencies spawn npm ENOENT. Please ensure that you have node and npm installed
[12/08/2019 16:26:24] [ERROR] Failed to activate extension: Error: spawn npm ENOENT

**Comment by cazfletch** [comment] 2019-08-12 16:02
The problem is that from within vscode it isn't finding npm. I thought that running `npm --version` from the vscode terminal would show the same problem. I suspect it's something to do with the path environment variable.

As a work around you can follow these instructions https://github.com/IBM-Blockchain/blockchain-vscode-extension/issues/1205#issuecomment-517178393

**Comment by feras-shamashan-coriel** [comment] 2019-08-13 09:32
Hi @cazfletch , I followed your instructions and all worked perfectly. Thank you so much :)

**Comment by Prudvi01** [comment] 2019-09-05 13:22
I tried various solutions but didn't help. I finally tried uninstalling node and downloading from [https://nodejs.org/en/](their website) and it simply worked. Maybe it was related to $PATH not being set properly, hope this helps someone.

**Comment by Krishna812** [comment] 2020-02-01 06:52
![image](https://user-images.githubusercontent.com/37139394/73588300-54199500-4495-11ea-8a76-af05a5e008b8.png)

I tried to uninstall and reinstallation of node, vs code and ibm extensions. but it didnt work. Kindly help to resolve this issue

**Comment by Sinha199** [comment] 2020-02-29 20:14
> ![image](https://user-images.githubusercontent.com/37139394/73588300-54199500-4495-11ea-8a76-af05a5e008b8.png)
> 
> I tried to uninstall and reinstallation of node, vs code and ibm extensions. but it didnt work. Kindly help to resolve this issue
> 
> PS C:\Users\kishu> node -v
> v12.14.1
> PS C:\Users\kishu> npm -v
> 6.13.4

the node version should be 8.x or 10.x only

**Comment by Sinha199** [comment] 2020-02-29 20:55
@cazfletch 
`Could not rebuild native dependencies Failed to execute command "npm" with  arguments "rebuild, grpc, --target=6.1.6, --runtime=electron, --update-binary, --fallback-to-build, --target_arch=x64, --dist-url=https://atom.io/download/electron" return code 1. Please ensure that you have node and npm installed`

The following issue is being shown. All the related versions and dependencies have been installed correctly.

**Comment by cazfletch** [comment] 2020-03-02 10:56
Hi @Sinha199 can you open a seperate issue for this please

**Comment by Pdarsh** [comment] 2020-05-19 10:06
* IBM Blockchain Platform Extension Version:1.0.28
* Visual Studio Code version:1.45.1
* Node.js v8.15.0, npm v6.4.1:
* Operating System and version: Ubuntu 18.04



Problem-
Could not rebuild native dependencies Failed to execute command "npm" with  arguments "rebuild, grpc, --target=7.2.4, --runtime=electron, --update-binary, --fallback-to-build, --target_arch=x64, --dist-url=https://atom.io/download/electron" return code 1. Please ensure that you have node and npm installed

**Comment by cazfletch** [comment] 2020-05-19 10:12
Hi @Pdarsh could you post the output from the blockchain output please

**Comment by Pdarsh** [comment] 2020-05-19 10:22
![VirtualBox_ubuntu_19_05_2020_15_50_03](https://user-images.githubusercontent.com/47714601/82315252-a8b33280-99e8-11ea-882e-4a46ee8f9216.png)

**Comment by cazfletch** [comment] 2020-05-19 11:31
@Pdarsh can you switch from the terminal view to the output view and post the contents of it please

**Comment by Pdarsh** [comment] 2020-05-21 05:11
the output view is empty

**Comment by Pdarsh** [comment] 2020-05-21 05:26
it started working thanks for your concern..

**Comment by littlestar642** [comment] 2020-05-23 10:33
Seems like the ideal configuration of your machine that should make the extension work is

node: 10.20.1
npm - 6.14.4
vscode - version - 1.39.0
extension version - 1.0.27

You should ensure that you are using the correct versions of these softwares and remove and conflicting files that might pose problems for example other code versions. I would recommend to use nvm for setting your node versions

**Comment by yasharne** [comment] 2020-05-23 17:54
The solution for me was to download the latest version of `vsix` file from the GitHub page

**Comment by subhodi** [comment] 2020-09-17 07:50
I had installed Node using NVM and VScode could not pick that up. Installed NodeJS v10 from this digitalocean link (https://www.digitalocean.com/community/tutorials/how-to-install-node-js-on-ubuntu-18-04)
```bash
cd  ~
curl -sL https://deb.nodesource.com/setup_10.x -o nodesource_setup.sh
sudo bash nodesource_setup.sh
sudo apt install nodejs
```

You can try installing Node 10 from the official website too.
