### ISSUE TITLE
IBP not detecting NPM and Nodejs

### ISSUE THREAD

**Issue by Kido0** [IBM-Blockchain/blockchain-vscode-extension#1401] opened 2019-09-13 10:03 UTC
## Description
IBP v1.10 cannot detect NPM and Nodejs although they're currently installed.

## Expected Behavior
Prerequisites page should remove required programs if they're installed and working. And IBP should then start.

## Actual Behavior
IBP doesn't detect Nodejs and NPM. Current version line is blank as if NPM and Node were not installed, although I made sure to install the versions I was being asked. VSCode displays the following error messages>
"Failed to activate extension: npm spawn ENOENT"
"Could not rebuild native dependencies spawn npm ENOENT. Please ensure that you have node and npm installed."

## Steps to Reproduce
1.
2.
3.

## Existing issues
- [ ] 
- [ ] 

## Log File

[13/9/2019 11:33:46] [IMPORTANT] Log files can be found by running the `Developer: Open Logs Folder` command from the palette

[13/9/2019 11:33:46] [INFO] Starting IBM Blockchain Platform Extension
[13/9/2019 11:33:51] [INFO] Attempting to require dependency: grpc
[13/9/2019 11:33:51] [INFO] Error requiring dependency: The gRPC binary module was not installed. This may be fixed by running "npm rebuild"
Original error: Cannot find module '/home/luca/.vscode/extensions/ibmblockchain.ibm-blockchain-platform-1.0.10/node_modules/grpc/src/node/extension_binary/node-v69-linux-x64-glibc/grpc_node.node'
[13/9/2019 11:33:56] [INFO] Updating native node modules
[13/9/2019 11:33:56] [INFO] Rebuilding native node modules
[13/9/2019 11:33:56] [ERROR] Could not rebuild native dependencies spawn npm ENOENT. Please ensure that you have node and npm installed
[13/9/2019 11:33:56] [ERROR] Failed to activate extension: Error: spawn npm ENOENT

## Environment

* IBM Blockchain Platform Extension Version: v1.0.10
* Visual Studio Code version: 1.38.0
* Environment name and version (e.g. Node.js v8.12.0, npm v6.4.1): Node.js v10.0.0, npm v6.4.1
* Operating System and version: Ubuntu 18.04.2 LTS

**Comment by Jakeeyturner** [comment] 2019-09-13 12:03
Hello - this could be caused by [this bug.](https://github.com/IBM-Blockchain/blockchain-vscode-extension/issues/1395)

Did you install Node/npm using `nvm`?

**Comment by Kido0** [comment] 2019-09-16 09:03
***Update***
Found a temporary solution by restoring a previous virtual machine state, and then downgrading the IBP to 1.0.9. Now it's working fine!

**Comment by Jakeeyturner** [comment] 2019-09-18 08:03
Closing this issue as the problem turned out to be another installation of Node/npm taking priority over the Node/npm installed using `nvm`.

**Closed by Jakeeyturner** 2019-09-18 08:03 UTC
Labels: question
