### ISSUE TITLE
Discovery service Error

### ISSUE THREAD

**Issue by mahdihazza** [IBM-Blockchain/blockchain-vscode-extension#2961] opened 2021-02-12 16:38 UTC
![image](https://user-images.githubusercontent.com/73389534/107795185-69442780-6d69-11eb-8e91-b34611c34f3d.png)

**Comment by Jakeeyturner** [comment] 2021-02-17 11:26
Hi @mahdihazza,

Are you trying to connect to a local environment created using the extension? If so, are you able to submit transactions using the extension?

Thanks,
Jake

**Comment by mahdihazza** [comment] 2021-02-17 13:52
Using the extension yes I can. but for the external app I could not.

**Comment by Jakeeyturner** [comment] 2021-02-17 16:04
Hi @mahdihazza,

In which case, the problem is with your client application code and not with the extension.

You could try running the `>Generate tests for smart contract(s)` command and look/copy the code which connect to a gateway and submit transactions.

Alternatively, I'd recommend asking your question on `fabric-questions` over at https://chat.hyperledger.org/

Closing issue.

**Closed by Jakeeyturner** 2021-02-17 16:04 UTC
Labels: external
