### ISSUE TITLE
Cannot add gateway connection

### ISSUE THREAD

**Issue by DennisM330** [IBM-Blockchain/blockchain-vscode-extension#685] opened 2019-03-04 23:46 UTC
## Description
Error trying to add a gateway connection to an external Hyperledger Fabric v1.4 instance running on  Ubuntu Linux.

## Expected Behavior
The gateway connection should be added with no errors. Worked in 0.3.0 of the extension.

## Actual Behavior
The following error is encountered: "Failed to add a new connection: /home/blockchain/workspace/fabric-getting-started/fabric-samples/commercial-paper/organization/digibank/gateway/networkConnection.yaml: Unexpected number in JSON at position 1"

## Your Environment
* IBM Blockchain Platform Extension Version: 0.3.1
* Visual Studio Code version: 1.31.1
* Environment name and version (e.g. Node.js v8.12.0, npm v6.4.1):  Node 8.11.1, npm 5.6
* Operating System and version: Ubuntu 16.04 LTS
* Link to your project:

**Comment by DennisM330** [comment] 2019-03-04 23:47
[networkConnection.yaml.txt](https://github.com/IBM-Blockchain/blockchain-vscode-extension/files/2928639/networkConnection.yaml.txt)

**Comment by DennisM330** [comment] 2019-03-05 00:01
[3-Blockchain.log](https://github.com/IBM-Blockchain/blockchain-vscode-extension/files/2928674/3-Blockchain.log)

**Comment by DennisM330** [comment] 2019-03-05 00:02
I made several attempts to add the gateway connection and then deleted the connection as shown in the log above.

**Comment by dan-yave** [comment] 2019-03-05 00:34
I'm having the same issue(s) - cant connect to my network and even local_fabric is now failing. I did an update to vs code today and it appears that the extension updated as well - everything was working fine prior to the update

**Comment by dan-yave** [comment] 2019-03-05 00:56
I have rolled back to my previous version 0.2.2 and all is working again. 

@DennisM330  you can right click on the installed extension and choose "Install Another Version..." if you want to rollback

**Comment by DennisM330** [comment] 2019-03-05 01:00
Thanks I may revert back to 0.3.0 depending if there is not an obvious workaround

**Comment by Jakeeyturner** [comment] 2019-03-05 09:25
Thanks for creating an issue.

The problem is coming from the ['Copy connection profile'](https://github.com/Jakeeyturner/blockchain-vscode-extension/commit/082b7f74b055208e6df8519d7ee3d503b9c17a3d) changes and support wasn't added for `yaml` connection profiles. Whilst I work on a fix for this, a temporary workaround would be to use a `json` connection profile when adding a new gateway instead.

**Comment by austingrice** [comment] 2019-03-07 17:47
I just ran into this error. I'm glad I could find it being resolved and being merged. Great work team!

**Closed** 2019-03-11 10:44 UTC
Labels: bug, sev2
