### ISSUE TITLE
Typescript smart contract packing issues

### ISSUE THREAD

**Issue by Tobias-Hunter** [IBM-Blockchain/blockchain-vscode-extension#1767] opened 2019-12-16 11:17 UTC
The first time I packaged my smart contract project I was able to install but not instantiate on Local Fabric (and subsequently on IBP), I changed the version and I was able to do both, why did the first package fail to instantiate..?

Here's the 2 .cds packages: [Archive.zip](https://github.com/IBM-Blockchain/blockchain-vscode-extension/files/3967715/Archive.zip) (just the basic project created from the VSCode extension)

Not too sure what could be done here, but it feels like an odd behaviour that it just worked the second time around - perhaps validating that the package was packaged ok before being let loose with it? This issue has been raised a few times on IBP with different people! 😢

**Comment by Tobias-Hunter** [comment] 2019-12-16 11:18
If you need any more information etc etc - please lemme know! 😎

**Comment by cazfletch** [comment] 2019-12-16 13:50
I just tried both packages and the first one fails with the error

```
Error: Cannot find module '/usr/local/src/dist/index.js'
[12/16/2019 1:31:17 PM] [INFO] fabricvscodelocalfabric-peer0.org1.example.com-typescript-0.0.1|    at Function.Module._resolveFilename (module.js:548:15)
[12/16/2019 1:31:17 PM] [INFO] fabricvscodelocalfabric-peer0.org1.example.com-typescript-0.0.1|    at Function.Module._load (module.js:475:25)
[12/16/2019 1:31:17 PM] [INFO] fabricvscodelocalfabric-peer0.org1.example.com-typescript-0.0.1|    at Module.require (module.js:597:17)
[12/16/2019 1:31:17 PM] [INFO] fabricvscodelocalfabric-peer0.org1.example.com-typescript-0.0.1|    at require (internal/module.js:11:18)
[12/16/2019 1:31:17 PM] [INFO] fabricvscodelocalfabric-peer0.org1.example.com-typescript-0.0.1|    at Function.getInfoFromContract (/usr/local/src/node_modules/```

And the second one instantiated fine. 

Had a look inside the cds and it looks like the first one the typescript isn't being compiled, is this something you can reproduce easily?

**Comment by Jakeeyturner** [comment] 2021-02-17 11:17
Closing - packaging has changed since.

**Closed by Jakeeyturner** 2021-02-17 11:17 UTC
Labels: bug
