### ISSUE TITLE
Could not rebuild native dependencies 

### ISSUE THREAD

**Issue by yasharne** [IBM-Blockchain/blockchain-vscode-extension#2355] opened 2020-05-22 19:31 UTC
## Description

I cannot install the latest update of the blockchain vscode extention with the following error:
![image](https://user-images.githubusercontent.com/7656049/82702865-0dd88380-9c88-11ea-9e05-3192d353a10d.png)

Here is the output log:

```
[5/22/2020 11:53:36 PM] [INFO] ../deps/grpc/src/core/lib/iomgr/iomgr_uv.cc:41:53: fatal error: opening dependency file ./Release/.deps/Release/obj.target/grpc/deps/grpc/src/core/lib/iomgr/iomgr_uv.o.d.raw: No such file or directory
[5/22/2020 11:53:36 PM] [INFO] compilation terminated.
[5/22/2020 11:53:36 PM] [INFO] grpc.target.mk:539: recipe for target 'Release/obj.target/grpc/deps/grpc/src/core/lib/iomgr/iomgr_uv.o' failed
[5/22/2020 11:53:36 PM] [INFO] make: Leaving directory '/home/yashar/.vscode/extensions/ibmblockchain.ibm-blockchain-platform-1.0.28/node_modules/grpc/build'
[5/22/2020 11:53:36 PM] [INFO] make: *** [Release/obj.target/grpc/deps/grpc/src/core/lib/iomgr/iomgr_uv.o] Error 1
[5/22/2020 11:53:36 PM] [INFO] gyp
[5/22/2020 11:53:36 PM] [INFO]  
[5/22/2020 11:53:36 PM] [INFO] ERR! build error 
[5/22/2020 11:53:36 PM] [INFO] gyp
[5/22/2020 11:53:36 PM] [INFO]  ERR! stack Error: `make` failed with exit code: 2
[5/22/2020 11:53:36 PM] [INFO] gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
[5/22/2020 11:53:36 PM] [INFO] gyp 
[5/22/2020 11:53:36 PM] [INFO] ERR! stack     at ChildProcess.emit (events.js:198:13)
[5/22/2020 11:53:36 PM] [INFO] gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)
[5/22/2020 11:53:36 PM] [INFO] gyp ERR! System Linux 5.3.0-51-generic
[5/22/2020 11:53:36 PM] [INFO] gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--library=static_library" "--module=/home/yashar/.vscode/extensions/ibmblockchain.ibm-blockchain-platform-1.0.28/node_modules/grpc/src/node/extension_binary/electron-v7.2-linux-x64-glibc/grpc_node.node" "--module_name=grpc_node" "--module_path=/home/yashar/.vscode/extensions/ibmblockchain.ibm-blockchain-platform-1.0.28/node_modules/grpc/src/node/extension_binary/electron-v7.2-linux-x64-glibc" "--napi_version=6" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=electron-v7.2"
[5/22/2020 11:53:36 PM] [INFO] gyp
[5/22/2020 11:53:36 PM] [INFO]  ERR! cwd /home/yashar/.vscode/extensions/ibmblockchain.ibm-blockchain-platform-1.0.28/node_modules/grpc
[5/22/2020 11:53:36 PM] [INFO] gyp ERR! node -v v10.20.1
[5/22/2020 11:53:36 PM] [INFO] gyp ERR! node-gyp -v v5.1.0
[5/22/2020 11:53:36 PM] [INFO] gyp ERR! not ok 
[5/22/2020 11:53:36 PM] [INFO] node-pre-gyp ERR! build error 
[5/22/2020 11:53:36 PM] [INFO] node-pre-gyp ERR! stack Error: Failed to execute '/usr/bin/node /usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --library=static_library --module=/home/yashar/.vscode/extensions/ibmblockchain.ibm-blockchain-platform-1.0.28/node_modules/grpc/src/node/extension_binary/electron-v7.2-linux-x64-glibc/grpc_node.node --module_name=grpc_node --module_path=/home/yashar/.vscode/extensions/ibmblockchain.ibm-blockchain-platform-1.0.28/node_modules/grpc/src/node/extension_binary/electron-v7.2-linux-x64-glibc --napi_version=6 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=electron-v7.2' (1)
[5/22/2020 11:53:36 PM] [INFO] node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/home/yashar/.vscode/extensions/ibmblockchain.ibm-blockchain-platform-1.0.28/node_modules/grpc/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
[5/22/2020 11:53:36 PM] [INFO] node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:198:13)
[5/22/2020 11:53:36 PM] [INFO] node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:982:16)
[5/22/2020 11:53:36 PM] [INFO] node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
[5/22/2020 11:53:36 PM] [INFO] node-pre-gyp ERR! System Linux 5.3.0-51-generic
[5/22/2020 11:53:36 PM] [INFO] node-pre-gyp ERR! command "/usr/bin/node" "/home/yashar/.vscode/extensions/ibmblockchain.ibm-blockchain-platform-1.0.28/node_modules/grpc/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build" "--library=static_library"
[5/22/2020 11:53:36 PM] [INFO] node-pre-gyp ERR! UNCAUGHT EXCEPTION 
[5/22/2020 11:53:36 PM] [INFO] node-pre-gyp ERR! stack Error: ENOENT: no such file or directory, uv_cwd
[5/22/2020 11:53:36 PM] [INFO] node-pre-gyp ERR! stack     at errorMessage (/home/yashar/.vscode/extensions/ibmblockchain.ibm-blockchain-platform-1.0.28/node_modules/grpc/node_modules/node-pre-gyp/bin/node-pre-gyp:120:28)
[5/22/2020 11:53:36 PM] [INFO] node-pre-gyp ERR! stack     at /home/yashar/.vscode/extensions/ibmblockchain.ibm-blockchain-platform-1.0.28/node_modules/grpc/node_modules/node-pre-gyp/bin/node-pre-gyp:86:7
[5/22/2020 11:53:36 PM] [INFO] node-pre-gyp ERR! stack     at /home/yashar/.vscode/extensions/ibmblockchain.ibm-blockchain-platform-1.0.28/node_modules/grpc/node_modules/node-pre-gyp/lib/build.js:27:20
[5/22/2020 11:53:36 PM] [INFO] node-pre-gyp ERR! 
[5/22/2020 11:53:36 PM] [INFO] stack     at ChildProcess.<anonymous> (/home/yashar/.vscode/extensions/ibmblockchain.ibm-blockchain-platform-1.0.28/node_modules/grpc/node_modules/node-pre-gyp/lib/util/compile.js:83:20)
[5/22/2020 11:53:36 PM] [INFO] node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:198:13)
[5/22/2020 11:53:36 PM] [INFO] node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:982:16)
[5/22/2020 11:53:36 PM] [INFO] node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
[5/22/2020 11:53:36 PM] [INFO] node-pre-gyp ERR! System Linux 5.3.0-51-generic
[5/22/2020 11:53:36 PM] [INFO] node-pre-gyp ERR! command "/usr/bin/node" "/home/yashar/.vscode/extensions/ibmblockchain.ibm-blockchain-platform-1.0.28/node_modules/grpc/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build" "--library=static_library"
[5/22/2020 11:53:36 PM] [INFO] /home/yashar/.vscode/extensions/ibmblockchain.ibm-blockchain-platform-1.0.28/node_modules/grpc/node_modules/node-pre-gyp/bin/node-pre-gyp:120
[5/22/2020 11:53:36 PM] [INFO]   log.error('cwd', process.cwd());
[5/22/2020 11:53:36 PM] [INFO]                            ^
[5/22/2020 11:53:36 PM] [INFO] Error: ENOENT: no such file or directory, uv_cwd
[5/22/2020 11:53:36 PM] [INFO]     at errorMessage (/home/yashar/.vscode/extensions/ibmblockchain.ibm-blockchain-platform-1.0.28/node_modules/grpc/node_modules/node-pre-gyp/bin/node-pre-gyp:120:28)
[5/22/2020 11:53:36 PM] [INFO]     at issueMessage (/home/yashar/.vscode/extensions/ibmblockchain.ibm-blockchain-platform-1.0.28/node_modules/grpc/node_modules/node-pre-gyp/bin/node-pre-gyp:126:3)
[5/22/2020 11:53:36 PM] [INFO]     at process.<anonymous> (/home/yashar/.vscode/extensions/ibmblockchain.ibm-blockchain-platform-1.0.28/node_modules/grpc/node_modules/node-pre-gyp/bin/node-pre-gyp:111:3)
[5/22/2020 11:53:36 PM] [INFO]     at process.emit (events.js:198:13)
[5/22/2020 11:53:36 PM] [INFO]     at process._fatalException (internal/bootstrap/node.js:497:27)
[5/22/2020 11:53:36 PM] [INFO] npm
[5/22/2020 11:53:36 PM] [INFO]  ERR! code ELIFECYCLE
[5/22/2020 11:53:36 PM] [INFO] npm ERR! errno 7
[5/22/2020 11:53:36 PM] [INFO] npm
[5/22/2020 11:53:36 PM] [INFO]  ERR! grpc@1.24.2 install: `node-pre-gyp install --fallback-to-build --library=static_library`
[5/22/2020 11:53:36 PM] [INFO] npm ERR! Exit status 7
[5/22/2020 11:53:36 PM] [INFO] npm ERR! 
[5/22/2020 11:53:36 PM] [INFO] npm ERR! Failed at the grpc@1.24.2 install script.
[5/22/2020 11:53:36 PM] [INFO] npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
[5/22/2020 11:53:36 PM] [INFO] npm
[5/22/2020 11:53:36 PM] [INFO]  WARN Local package.json exists, but node_modules missing, did you mean to install?
[5/22/2020 11:53:36 PM] [INFO] npm ERR! A complete log of this run can be found in:
[5/22/2020 11:53:36 PM] [INFO] npm ERR!     /home/yashar/.npm/_logs/2020-05-22T19_23_36_564Z-debug.log
[5/22/2020 11:53:36 PM] [ERROR] Could not rebuild native dependencies Failed to execute command "npm" with  arguments "rebuild, grpc, --target=7.2.4, --runtime=electron, --update-binary, --fallback-to-build, --target_arch=x64, --dist-url=https://atom.io/download/electron" return code 7. Please ensure that you have node and npm installed
[5/22/2020 11:53:36 PM] [ERROR] Failed to activate extension: Error: Failed to execute command "npm" with  arguments "rebuild, grpc, --target=7.2.4, --runtime=electron, --update-binary, --fallback-to-build, --target_arch=x64, --dist-url=https://atom.io/download/electron" return code 7
[5/22/2020 11:53:36 PM] [ERROR] Error: Failed to execute command "npm" with  arguments "rebuild, grpc, --target=7.2.4, --runtime=electron, --update-binary, --fallback-to-build, --target_arch=x64, --dist-url=https://atom.io/download/electron" return code 7
	at ChildProcess.<anonymous> (/home/yashar/.vscode/extensions/ibmblockchain.ibm-blockchain-platform-1.0.28/build/extension/util/CommandUtil.js:76:39)
	at ChildProcess.emit (events.js:203:13)
	at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
```

## Your Environment

* IBM Blockchain Platform Extension Version:1.0.28 trying to update to 1.0.30
* Visual Studio Code version: 1.45.1
* Environment name and version (e.g. Node.js v8.12.0, npm v6.4.1): node v10.20.1, npm v6.14.5
* Operating System and version: ubuntu 18.04 5.3.0-51-generic

**Comment by ElangSBP** [comment] 2020-05-22 23:37
Hi, Try to uninstall the extension first and reinstall it again, if it's still doesn't successful then try to download the latest VSIX from this page >>https://github.com/IBM-Blockchain/blockchain-vscode-extension/releases and install it manually in VSCode

Notes: If you see in the build status in VSCode Marketplace it's shown v1.0.30 but in when you install it's still in v1.0.28, the latest one is 1.0.30.

Tested by me : VSCode 1.46.0-Insider, Node 10.20.1, Linux Mint 19.3 Tricia

**Comment by yasharne** [comment] 2020-05-23 16:04
Thanks @ElangSBP , manual installation solved the problem. I lost about 90Gb of my bandwidth because this plugin was retrying to download and install itself, I guess there should be a prevention mechanism to prevent such problems

**Comment by ElangSBP** [comment] 2020-05-23 19:18
Try to turn-off the Automatic Update for Plugin for temporary measure

**Comment by sstone1** [comment] 2020-05-23 20:16
This is a duplicate of https://github.com/IBM-Blockchain/blockchain-vscode-extension/issues/2349

The VSCode marketplace has become corrupted, at least for our extension and a few others. The new version is shown as available in some APIs, but when VSCode tries to download it, it gets the old version. This results in a infinite update loop. They reported some issues with the marketplace this week on the status page, which is likely involved. 

We as the authors of this extension cannot do anything about this issue. We have raised it with the VSCode team and are waiting for their response.

**Closed** 2020-05-26 09:47 UTC
Labels: external
