### ISSUE TITLE
IBM Blockchain Platform Extension for VS Code disconnects from WSL Ubuntu

### ISSUE THREAD

**Issue by bizbi** [IBM-Blockchain/blockchain-vscode-extension#1357] opened 2019-08-30 13:18 UTC
_(Moved to this repository by request of @cazfletch)_

On opening the extension, for example by clicking where the icon should be, it shows the panels for the extension but at the bottom left hand side instead of "WSL: Ubuntu" it changes to "Disconnected from WSL: Ubuntu", and brings up a dialog "Attempting to reconnect..." which hangs.

Also, the Extension icon is not shown in the navigation bar, just a blank spot where it should be (still clickable to open the extension).

Prior to installing VS Code, Docker Desktop was running Hyperledger Fabric containers, i.e., Linux has the necessary Node packages installed.  The same behaviour occurs in VS Code on removing the containers and quitting Docker.

Windows 10 Pro 10.0.18362
Visual Studio Code 1.37.1
IBM Blockchain Platform Extension for VS Code 1.0.8

![VS Code before opening IBM Blockchain Extension](https://user-images.githubusercontent.com/2794023/64023766-f2917b00-cb30-11e9-927b-35086e8ba98b.PNG)

![VS Code after opening IBM Blockchain Extension](https://user-images.githubusercontent.com/2794023/64023778-f7562f00-cb30-11e9-8b02-4bc3410acdb1.PNG)

**Comment by cazfletch** [comment] 2019-09-02 10:07
Hi @keith-harrison-broninski i tried this out using ssh rather than wsl. I don't get exactly the same problem however i do get problems. For now the answer is that the extension doesn't work with remote development but we plan to make it work in the future

**Comment by keith-harrison-broninski** [comment] 2019-09-02 13:21
@cazfletch Thanks. Do you have a timeframe for implementing this? Seems like something a lot of people would find useful!

**Comment by mattcarp** [comment] 2019-09-02 15:10
I can confirm that this extension also does not work using remote development via SSH on an EC2 Ubuntu server (18.04). However, error messages are of the type: `command 'aPackagesExplorer.createSmartContractProjectEntry' not found` (in other words, commands from the  `activationEvents` key in package.json.

I've tried rebuilding grpc in the `~/.vscode-server/extensions/ibmblockchain.ibm-blockchain-platform-1.0.8` directory using the following:

`npm rebuild grpc --target=4.2.5 --runtime=electron --dist-url=https://atom.io/download/electron --update-binary --fallback-to-build --target_arch=x64`

But no luck. 

Works well locally on my Mac though. Would be great to have this running for remote development since it would simplify setting up dev chains in the cloud.

Thanks.

**Comment by EdMoffatt** [comment] 2019-10-15 14:54
Hey @bizbi  - thank you for raising! @cazfletch 's looking into the fix for this :)

Not related to this issue specifically, but I was wondering if you would mind letting me know why you use Remote Development? I'd not heard of it until folks raised issues, so it wasn't a usage-pattern I'd thought of before. I'm a User Experience Designer working on this dev tooling, so I appreciate any chance to learn about how people want to use it!

GitHub reply is fine, or you could drop me an email edmoffat@uk.ibm.com if you prefer! Interested if you use Remote Dev to gain particular advantages for your workflow, or maybe to work around some restrictions you have? Cheers!

**Comment by bizbi** [comment] 2019-10-15 15:46
Hi Ed

I am prototyping with fabric on a Windows laptop, so building a dev
environment in WSL.  Actually, now I've got further with it, I probably
wouldn't run fabric in VS Code any more, since set up, test, and tear down
of the environment is all scripted.  But it would have been useful when
doing the tutorial early on.

Hope this helps,

Best, Keith

**Comment by cazfletch** [comment] 2020-02-05 16:09
closing as not going to support WSL

**Closed by cazfletch** 2020-02-05 16:09 UTC
Labels: bug, external
