### ISSUE TITLE
Local Fabric is not getting started! 

### ISSUE THREAD

**Issue by saicharanpogul** [IBM-Blockchain/blockchain-vscode-extension#1786] opened 2019-12-21 05:32 UTC
**#1460** 

**Now I'm doing it windows 10 pro and I'm getting this:** 

$ generate.cmd

C:\Users\Saicharan Pogul\.fabric-vscode\environments\local_fabric>rem

C:\Users\Saicharan Pogul\.fabric-vscode\environments\local_fabric>rem Copyright                                                                                                                 IBM Corp All Rights Reserved

C:\Users\Saicharan Pogul\.fabric-vscode\environments\local_fabric>rem

C:\Users\Saicharan Pogul\.fabric-vscode\environments\local_fabric>rem SPDX-Licen                                                                                                                se-Identifier: Apache-2.0

C:\Users\Saicharan Pogul\.fabric-vscode\environments\local_fabric>rem

C:\Users\Saicharan Pogul\.fabric-vscode\environments\local_fabric>rem rewrite pa                                                                                                                ths for Windows users to enable Docker socket binding

C:\Users\Saicharan Pogul\.fabric-vscode\environments\local_fabric>set COMPOSE_CO                                                                                                                NVERT_WINDOWS_PATHS=1

C:\Users\Saicharan Pogul\.fabric-vscode\environments\local_fabric>set CHANNEL_NA                                                                                                                ME=mychannel

C:\Users\Saicharan Pogul\.fabric-vscode\environments\local_fabric>rem teardown a                                                                                                                ny existing network

C:\Users\Saicharan Pogul\.fabric-vscode\environments\local_fabric>cmd /c .\teard                                                                                                                own.cmd

C:\Users\Saicharan Pogul\.fabric-vscode\environments\local_fabric>rem

C:\Users\Saicharan Pogul\.fabric-vscode\environments\local_fabric>rem Copyright                                                                                                                 IBM Corp All Rights Reserved

C:\Users\Saicharan Pogul\.fabric-vscode\environments\local_fabric>rem

C:\Users\Saicharan Pogul\.fabric-vscode\environments\local_fabric>rem SPDX-Licen                                                                                                                se-Identifier: Apache-2.0

C:\Users\Saicharan Pogul\.fabric-vscode\environments\local_fabric>rem

C:\Users\Saicharan Pogul\.fabric-vscode\environments\local_fabric>rem Shut down                                                                                                                 the Docker containers for the system tests.

C:\Users\Saicharan Pogul\.fabric-vscode\environments\local_fabric>docker-compose                                                                                                                 -f docker-compose.yml kill   && docker-compose -f docker-compose.yml down -v
Removing fabricvscodelocalfabric_ca.org1.example.com ... done
Removing network fabricvscodelocalfabric_basic
Removing volume fabricvscodelocalfabric_orderer.example.com
Removing volume fabricvscodelocalfabric_ca.org1.example.com
Removing volume fabricvscodelocalfabric_peer0.org1.example.com
Removing volume fabricvscodelocalfabric_couchdb

C:\Users\Saicharan Pogul\.fabric-vscode\environments\local_fabric>rem remove chaincode docker images

C:\Users\Saicharan Pogul\.fabric-vscode\environments\local_fabric>for /F "tokens=*" %i in ('docker ps -aq --filter "name=fabricvscodelocalfabric-*"') do docker rm -f %i

C:\Users\Saicharan Pogul\.fabric-vscode\environments\local_fabric>for /F "tokens=*" %i in ('docker images -aq "fabricvscodelocalfabric-*"') do docker rmi -f %i

C:\Users\Saicharan Pogul\.fabric-vscode\environments\local_fabric>rem remove previous crypto material and config transactions

C:\Users\Saicharan Pogul\.fabric-vscode\environments\local_fabric>for %d in (admin-msp configtx crypto-config wallets\local_fabric_wallet) do (
pushd %d
 rmdir /q/s .
 popd
)

C:\Users\Saicharan Pogul\.fabric-vscode\environments\local_fabric>(
pushd admin-msp
 rmdir /q/s .
 popd
)
The process cannot access the file because it is being used by another process.

C:\Users\Saicharan Pogul\.fabric-vscode\environments\local_fabric>(
pushd configtx
 rmdir /q/s .
 popd
)
The process cannot access the file because it is being used by another process.

C:\Users\Saicharan Pogul\.fabric-vscode\environments\local_fabric>(
pushd crypto-config
 rmdir /q/s .
 popd
)
The process cannot access the file because it is being used by another process.

C:\Users\Saicharan Pogul\.fabric-vscode\environments\local_fabric>(
pushd wallets\local_fabric_wallet
 rmdir /q/s .
 popd
)
The process cannot access the file because it is being used by another process.

C:\Users\Saicharan Pogul\.fabric-vscode\environments\local_fabric>rem Your system is now clean

C:\Users\Saicharan Pogul\.fabric-vscode\environments\local_fabric>del /f generate.complete

C:\Users\Saicharan Pogul\.fabric-vscode\environments\local_fabric>rem generate crypto material

C:\Users\Saicharan Pogul\.fabric-vscode\environments\local_fabric>docker run --rm -v C:\Users\Saicharan Pogul\.fabric-vscode\environments\local_fabric:/etc/hyperledger/fabric -w /etc/hyperledger/fabric hyperledger/fabric-tools:1.4.4 cryptogen generate --config=./crypto-config.yaml
docker: invalid reference format.
See 'docker run --help'.

C:\Users\Saicharan Pogul\.fabric-vscode\environments\local_fabric>rem rename the certificate authority private key

C:\Users\Saicharan Pogul\.fabric-vscode\environments\local_fabric>move /y .\crypto-config\peerOrganizations\org1.example.com\ca\*_sk .\crypto-config\peerOrganizations\org1.example.com\ca\ca.org1.example.com-key.pem
The system cannot find the path specified.

C:\Users\Saicharan Pogul\.fabric-vscode\environments\local_fabric>rem start the certificate authority

C:\Users\Saicharan Pogul\.fabric-vscode\environments\local_fabric>docker-compose -f docker-compose.yml up -d ca.org1.example.com
Creating network "fabricvscodelocalfabric_basic" with the default driver
Creating volume "fabricvscodelocalfabric_orderer.example.com" with default driver
Creating volume "fabricvscodelocalfabric_ca.org1.example.com" with default driver
Creating volume "fabricvscodelocalfabric_peer0.org1.example.com" with default driver
Creating volume "fabricvscodelocalfabric_couchdb" with default driver
Creating fabricvscodelocalfabric_ca.org1.example.com ... done

C:\Users\Saicharan Pogul\.fabric-vscode\environments\local_fabric>rem enroll the admin identity

C:\Users\Saicharan Pogul\.fabric-vscode\environments\local_fabric>docker run --network fabricvscodelocalfabric_basic --rm -v C:\Users\Saicharan Pogul\.fabric-vscode\environments\local_fabric:/etc/hyperledger/fabric hyperledger/fabric-ca:1.4.4 fabric-ca-client enroll -u http://admin:adminpw@ca.org1.example.com:17054 -M /etc/hyperledger/fabric/admin-msp
docker: invalid reference format.
See 'docker run --help'.

C:\Users\Saicharan Pogul\.fabric-vscode\environments\local_fabric>copy /y admin-msp\signcerts\cert.pem crypto-config\peerOrganizations\org1.example.com\msp\admincerts\
The system cannot find the path specified.

C:\Users\Saicharan Pogul\.fabric-vscode\environments\local_fabric>copy /y admin-msp\signcerts\cert.pem crypto-config\peerOrganizations\org1.example.com\peers\peer0.org1.example.com\msp\admincerts\
The system cannot find the path specified.

C:\Users\Saicharan Pogul\.fabric-vscode\environments\local_fabric>rem stop the certificate authority

C:\Users\Saicharan Pogul\.fabric-vscode\environments\local_fabric>docker-compose -f docker-compose.yml stop ca.org1.example.com
Stopping fabricvscodelocalfabric_ca.org1.example.com ... done

C:\Users\Saicharan Pogul\.fabric-vscode\environments\local_fabric>rem generate genesis block for orderer

C:\Users\Saicharan Pogul\.fabric-vscode\environments\local_fabric>docker run --rm -v C:\Users\Saicharan Pogul\.fabric-vscode\environments\local_fabric:/etc/hyperledger/fabric -w /etc/hyperledger/fabric hyperledger/fabric-tools:1.4.4 configtxgen -profile OneOrgOrdererGenesis -outputBlock ./configtx/genesis.block
docker: invalid reference format.
See 'docker run --help'.

C:\Users\Saicharan Pogul\.fabric-vscode\environments\local_fabric>rem generate channel configuration transaction

C:\Users\Saicharan Pogul\.fabric-vscode\environments\local_fabric>docker run --rm -v C:\Users\Saicharan Pogul\.fabric-vscode\environments\local_fabric:/etc/hyperledger/fabric -w /etc/hyperledger/fabric hyperledger/fabric-tools:1.4.4 configtxgen -profile OneOrgChannel -outputCreateChannelTx ./configtx/channel.tx -channelID mychannel
docker: invalid reference format.
See 'docker run --help'.

C:\Users\Saicharan Pogul\.fabric-vscode\environments\local_fabric>rem generate anchor peer transaction

C:\Users\Saicharan Pogul\.fabric-vscode\environments\local_fabric>docker run --rm -v C:\Users\Saicharan Pogul\.fabric-vscode\environments\local_fabric:/etc/hyperledger/fabric -w /etc/hyperledger/fabric hyperledger/fabric-tools:1.4.4 configtxgen -profile OneOrgChannel -outputAnchorPeersUpdate ./configtx/Org1MSPanchors.tx -channelID mychannel -asOrg Org1MSP
docker: invalid reference format.
See 'docker run --help'.

C:\Users\Saicharan Pogul\.fabric-vscode\environments\local_fabric>rem generate gateways, nodes, and wallets

C:\Users\Saicharan Pogul\.fabric-vscode\environments\local_fabric>node generate.js
fs.js:114
    throw err;
    ^

Error: ENOENT: no such file or directory, scandir 'C:\Users\Saicharan Pogul\.fabric-vscode\environments\local_fabric\admin-msp\keystore'
    at Object.readdirSync (fs.js:790:3)
    at Object.<anonymous> (C:\Users\Saicharan Pogul\.fabric-vscode\environments\local_fabric\generate.js:13:33)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)

C:\Users\Saicharan Pogul\.fabric-vscode\environments\local_fabric>rem mark the process as complete

C:\Users\Saicharan Pogul\.fabric-vscode\environments\local_fabric>copy /y nul generate.complete
        1 file(s) copied.
**docker: invalid reference format.**

**Comment by cazfletch** [comment] 2019-12-23 11:30
I think the problem is that cleaning up isn't working properly as it says "The process cannot access the file because it is being used by another process."  If you delete this folder `C:\Users\Saicharan Pogul.fabric-vscode\environments\local_fabric` and then close and reopen vscode it should fix the problem

**Comment by saicharanpogul** [comment] 2019-12-23 11:52
i did that, and I'm getting same error again.

**Comment by davidkel** [comment] 2019-12-23 11:55
@saicharanpogul It's possible that the environment doesn't work if you have a space in your username as you do. If you can could you try creating another account without putting a space in see if that fixes the problem for you ?

**Comment by saicharanpogul** [comment] 2019-12-23 11:58
yes i tried to rename the username but wasn't able to.
That's the only way i can do this?
Isn't it possible to rename the user?
Although i will try this in new user and report you.

**Comment by davidkel** [comment] 2020-01-13 13:41
This is highly lucky to be a bug in the fabric generator not allowing for userids with spaces

**Comment by miribeiro** [comment] 2020-02-05 19:29
> yes i tried to rename the username but wasn't able to.
> That's the only way i can do this?
> Isn't it possible to rename the user?
> Although i will try this in new user and report you.

I think I had the same error. 
Have you tried changing the configuration directory of the IBM Blockchain extension in VSCode settings to a directory without spaces (like C:\newFolder)? I believe it worked for me!

**Comment by cazfletch** [comment] 2020-02-10 15:49
@saicharanpogul can you try this on the latest version of the extension please (1.0.19)

**Comment by saicharanpogul** [comment] 2020-02-10 15:53
yeah I will try and let you know @cazfletch

**Comment by saicharanpogul** [comment] 2020-02-10 17:04
Yes its working.
**[SUCCESS] Connected to Local Fabric**

**Comment by cazfletch** [comment] 2020-02-10 17:05
closing as now works

**Closed by cazfletch** 2020-02-10 17:05 UTC
Labels: bug, external
