### ISSUE TITLE
Failed to determine workspace language type, supported languages are JavaScript, TypeScript, Go and Java. Please ensure your contract's root-level directory is open in the Explorer.

### ISSUE THREAD

**Issue by StevenJGreen** [IBM-Blockchain/blockchain-vscode-extension#939] opened 2019-05-08 05:11 UTC
## Description
When clicking on "Package a Smart Contract Project", I receive the error: Failed to determine workspace language type, supported languages are JavaScript, TypeScript, Go and Java. Please ensure your contract's root-level directory is open in the Explorer.

## Expected Behavior
This action should package up the commercial paper smart contract package for installing onto a peer.

## Actual Behavior
I receive the error: Failed to determine workspace language type, supported languages are JavaScript, TypeScript, Go and Java. Please ensure your contract's root-level directory is open in the Explorer.

## Log File

There is no Blockchain.log file

## Your Environment
* IBM Blockchain Platform Extension Version: 0.4.0
* Visual Studio Code version: 1.33.1
* Operating System and version: Ubuntu

**Comment by cazfletch** [comment] 2019-05-08 08:40
Hi @StevenJGreen can you send me a picture of what your folder structure looks like please?

**Comment by StevenJGreen** [comment] 2019-05-08 09:16
Hi resolved. In VSCode, I had to open the folder at the contract level not the magnetocorp level.

**Comment by cazfletch** [comment] 2019-05-08 09:43
closing as resolved

**Closed by cazfletch** 2019-05-08 09:43 UTC

**Comment by veasnasous2** [comment] 2020-02-05 22:50
I tried to do it too but it does not work

**Comment by cazfletch** [comment] 2020-02-06 09:27
@veasnasous2 can you create a new issue please with all the details in about the issue you are having please

**Comment by tobydickins** [comment] 2020-05-11 20:33
Trying to package up the IBM Loyalty Blockchain example and getting the same error when trying to package the contract. I have the contract folder open in explorer, but still get the "Failed to determine workspace language type, supported languages are JavaScript, TypeScript, Go and Java. Please ensure your contract's root-level directory is open in the Explorer." error message.

**Comment by cazfletch** [comment] 2020-05-12 08:37
Hey @tobydickins can you post a screen shot of the explorer view please

**Comment by tobydickins** [comment] 2020-05-12 13:11
Here it is, thanks for your help.

![screen](https://user-images.githubusercontent.com/65092153/81695336-788bf280-9430-11ea-9143-c8888bceb93b.png)

**Comment by cazfletch** [comment] 2020-05-12 13:21
@tobydickins The problem is that the contract folder needs to be the one you open in vscode. Currently it is a sub-folder.

**Comment by tobydickins** [comment] 2020-05-12 13:34
Hi, 

That worked, but now unable to install the packaged contract in the local environment.

![screen1](https://user-images.githubusercontent.com/65092153/81698060-7a0aea00-9433-11ea-9ba7-6b1fe001d50a.png)

**Comment by cazfletch** [comment] 2020-05-12 14:06
did you click install and then nothing happened?

**Comment by tobydickins** [comment] 2020-05-12 14:08
yes, only the INFO message in the OUTPUT window. No errors.

**Comment by cazfletch** [comment] 2020-05-12 16:07
@tobydickins can you raise a new issue for this please

**Comment by tobydickins** [comment] 2020-05-12 18:43
OK, created issue:

Difficulty in installing packaged Customer Loyalty Contract #2302
