### ISSUE TITLE
Instantiating node based chaincode with restricted internet

### ISSUE THREAD

**Issue by ashishchandr70** [IBM-Blockchain/blockchain-vscode-extension#1283] opened 2019-08-13 03:43 UTC
We have a restricted internet connection from our Linux VMs. I have successfully activated the IBP extension through help from @cazfletch but now I keep running into an error when instantiating node.js based chaincode.

## Description

Successful instantiation of a sample smart contract.
## Expected Behavior

We expect an error because of our internet restrictions.
## Actual Behavior

Error 500 - ENOTFOUND while trying to access registry.npmjs.org.

## Possible Fix

I want to point out that we do have access to a local npmjs artifactory so all of the packages are available but not from registry.npmjs.org but from our intranet based npmjs repo.

What would help is if we could find a way to get the scripts that are executed by the extension to use our registry instead of the npmjs.org.

## Steps to Reproduce

1. Open VS Code
2. Create a sample smart contract project and install chaincode
3. Try to instantiate.

## Your Environment

* IBM Blockchain Platform Extension Version: 1.0.5
* Visual Studio Code version: 1.36
* Environment name and version (e.g. Node.js v8.12.0, npm v6.4.1): 8.14
* Operating System and version: RHEL 7.6 'Maipo'
* Link to your project:

**Comment by davidkel** [comment] 2019-08-13 08:01
Unfortunately this isn't a supported environment for hyperledger fabric and cannot be solved by the vscode extension. The problem is not only having access to an alternative npm registry, but also you need to provide the node.js source code in order for native modules to be built. https://jira.hyperledger.org/browse/FAB-9287 describes the issue and some of the approaches people have taken. There are of course other ways you may be able to solve this problem. 
It boils down to
1. The chaincode builder needs to get npm modules from somewhere
2. The chaincode builder needs to get the right node.js source code from somewhere

One thing to bear in mind is that node.js chaincode is a node.js module, and thus you can provide a .npmrc as part of your chaincode package to influence what npm does. So for example the following entries may be of help
```
registry=<the url for your custom npm registry>
disturl=<the url for your custom server providing node.js source tarballs>
```
Good Luck

**Comment by cazfletch** [comment] 2019-08-13 08:09
closing as not an extension issue

**Closed by cazfletch** 2019-08-13 08:09 UTC
Labels: question
