### ISSUE TITLE
VM hangs after Blockchain - Create Smart Contract Project

### ISSUE THREAD

**Issue by lesleyannjordan** [IBM-Blockchain/blockchain-vscode-extension#135] opened 2018-10-04 11:42 UTC
Following screen shoots to Create my Smart Contract Folder - I get to the select folder screen and I loose ability to interact with my VM.  I have rebooted my VM and tried again and it hung at the same point.

Steps:
Settings - show command pallate
Blockchain - create smart contract project
  - first time round it installs some dependencies (isn't required second time after the reboot)
select javascript -> file dialogue window opens
file dialogue window has nothing selectable and I no longer can select anything within my VMWare window - side menus, background, exit button.  The only option I have is to 'Shutdown guest'
 

Details of VM:
VMWare
Ubunto 16.06
Memory 8GB

I have been able to create a smart contract via the command line:
yo fabric:chaincode -- --language javascript --name my-smart-contract --version 0.0.1 --description "My Smart Contract" --author "LA Jordan" --license Apache-2.0

I can then select the folder and package and then when connecting to a local fabric I get issue #131

**Comment by heatherlp** [comment] 2018-10-04 15:49
Rob doesn't hit this when he runs a ubuntu VM using virtual box

**Comment by rthatcher** [comment] 2018-10-04 15:58
I was able to create a smart contract inside VSC and did get the boilerplate contract code.

**BUT** when I read Lesley Ann's post in detail - my VM did seem to hang for a while and I was clicking between various things hoping to get input focus - I'm guessing it took between 1 and 2 mins before I had input focus back.

The 'hang' was at the point of selecting a folder.

I have only 4GB RAM for this VM and at the time it had no Fabric running - I would be surprised if memory was the issue.

**Comment by rthatcher** [comment] 2018-10-05 08:19
I have a workaround for this ...
When the dialog box comes up (unresponsive) use `alt`-`TAB` to Show Desktop.  Then use `alt`-`TAB` again to switch back to VSC and the dialog is responsive.

**Comment by lesleyannjordan** [comment] 2018-10-05 16:27
I have also been able to apply the same work-around.  However I have to keep doing alt-tab until I get all my screens to disappear, then when I re-open VSC the dialog is responsive

**Comment by rthatcher** [comment] 2018-10-11 13:36
(Testing with v0.0.3.)

Have noticed that 'most times' when I create a new package the dialog is 'live'!  But sometimes it still hangs.

Have not been able to find the pattern, but I'm wondering if it is related to the current view/selected item when starting the Create?

**Comment by Jakeeyturner** [comment] 2018-10-17 10:37
Seen this issue on a Ubuntu 16.04.4 LTS (Xenial Xerus) machine. The file browser seems to make VSCode hang, however it doesn't crash.

Following the instructions [here](https://github.com/Microsoft/vscode/wiki/Native-Crash-Issues) I wasn't able to get a 'core' file as VSCode doesn't crash and produce one, so I'm unable to read the stacktrace.

However, I think this issue may be related to https://github.com/Microsoft/vscode/issues/52778 as running VSCode in verbose mode also provides similar messages to https://github.com/Microsoft/vscode/issues/52778#issuecomment-400985165.

**Comment by mbwhite** [comment] 2018-10-22 13:36
It has been discovered that adding a small pause prior to opening these dialogs appears to workaround the problem. Certainly not a solution but permits the useability fo the plugin on Ubunutu.

200ms seems to be a suitable figure; until this can be pushed out and tested by various different people on different systems, it's impossible to say exactly how stable this will be. 

Updates have been posted to the vsCode issue mentioned above.

Add this code into the UserInputUtils and call before of the `showOpenDialog`

 ```
 /** Delay for a set number of ms; this code is added in order to workaround the VSCode issue
   * https://github.com/Microsoft/vscode/issues/52778
   *
   * See comment on this post for discussion.
   */
  public static delayWorkaround(ms: number) {
    return new Promise((resolve) => setTimeout(resolve, ms));
  }

```

```
              // see method comment for details of this workaround
              await UserInputUtil.delayWorkaround(200);
              const fileBrowser: vscode.Uri[] = await vscode.window.showOpenDialog({
                  canSelectFiles: false,
                  canSelectFolders: true,
                  canSelectMany: false,
                  openLabel: 'Select folder',
                  defaultUri: usersHome
              });
```

**Comment by mbwhite** [comment] 2018-10-22 15:34
https://github.com/IBM-Blockchain/blockchain-vscode-extension/pull/235

**Comment by DennisM330** [comment] 2018-10-22 21:12
I am running into the same issue with a Ubuntu VMWare image. Will a new version of the extension with the workaround above be available soon?

**Comment by mbwhite** [comment] 2018-10-25 08:19
Updated PR to push the timeout to 500ms
https://github.com/IBM-Blockchain/blockchain-vscode-extension/pull/250

**Comment by DennisM330** [comment] 2018-10-25 12:39
I can verify the workaround works on Ubuntu when generating a new Smart Contract. Seems the issue is there for the export of a package though.

**Comment by mbwhite** [comment] 2018-10-25 14:01
Suspect that we'll need to add the workaround for the other dialog types..

**Comment by caroline-church** [comment] 2019-01-07 11:01
closing

**Closed by caroline-church** 2019-01-07 11:01 UTC
Labels: blocked, bug
